import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
    sidebar: [
        "overview",
        "contributing",
        { type: "html", value: "<div style='background-color:var(--ifm-color-emphasis-600);height:1px;margin:.5rem'></div>" },
        {
            type: "category",
            label: "Data Model",
            link: {
                type: "doc",
                id: "domain/data-model"
            },
            items: [{
                type: "autogenerated",
                dirName: "data-model"
            }]
        },
        {
            type: "category",
            label: "Game Model",
            link: {
                type: "doc",
                id: "domain/game-model"
            },
            items: [{
                type: "autogenerated",
                dirName: "game-model"
            }]
        },
        {
            type: "category",
            label: "Presentation",
            link: {
                type: "doc",
                id: "domain/presentation"
            },
            items: [{
                type: "autogenerated",
                dirName: "presentation"
            }]
        },
        {
            type: "category",
            label: "Interaction",
            link: {
                type: "doc",
                id: "domain/interaction"
            },
            items: [{
                type: "autogenerated",
                dirName: "interaction"
            }]
        },
        {
            type: "category",
            label: "Host Services",
            link: {
                type: "doc",
                id: "domain/host-services"
            },
            items: [{
                type: "autogenerated",
                dirName: "host-services"
            }]
        },
        {
            type: "category",
            label: "Host Integration",
            link: {
                type: "doc",
                id: "domain/host-integration"
            },
            items: [{
                type: "autogenerated",
                dirName: "host-integration"
            }]
        },
        {
            type: "category",
            label: "Diagnostics",
            link: {
                type: "doc",
                id: "domain/diagnostics"
            },
            items: [{
                type: "autogenerated",
                dirName: "diagnostics"
            }]
        }
    ]
} satisfies SidebarsConfig;